### ISSUE TITLE
2.4Ghz keyboards not working

### ISSUE THREAD

**Issue by mtanaka14** [sebeksd/Multi-Keyboard-For-AutoHotkey#4]
I have two wireless keyboards that use receivers and they are not recognized by devices manager.
Bluetooth keyboards seems to work fine.

**Comment by sebeksd** [comment]
Did you disconnect and reconnect receiver or only turn off/on the keyboard itself? Try with receiver I think my worked this way. Right now I can't test it (will be back in a week then I will try it).

**Comment by sebeksd** [comment]
Nice to hear.  Closing.
